(module
  (import "env" "print_i32" (func $print_i32 (param i32)))
  (import "env" "print_f64" (func $print_f64 (param f64)))
  
  (memory 1)
  
  (func $main (export "main")
    (local $x i32)
    (local $y f64)
    (local $z f64)
    (local $a i32)
    (local $b i32)
    (i32.const 10)
    (local.set $x)
    (f64.const 3.14)
    (local.set $y)
    (local.get $x)
    (f64.convert_i32_s)
    (local.set $z)
    (local.get $z)
    (call $print_f64)
    (local.get $y)
    (i32.trunc_f64_s)
    (local.set $a)
    (local.get $a)
    (call $print_i32)
    (local.get $x)
    (f64.convert_i32_s)
    (local.get $y)
    (f64.add)
    (local.set $z)
    (local.get $z)
    (call $print_f64)
    (i32.const 1)
    (local.set $b)
    (local.get $b)
    (local.set $a)
    (local.get $a)
    (call $print_i32)
    (local.get $b)
    (f64.convert_i32_s)
    (local.set $y)
    (local.get $y)
    (call $print_f64)
  )
  
)
