(module
  (import "env" "print_i32" (func $print_i32 (param i32)))
  (import "env" "print_f64" (func $print_f64 (param f64)))
  
  (memory 1)
  
  (func $main (export "main")
    (local $p i32)
    (i32.const 0)
    (local.set $p)
    (local.get $p)
    (i32.const 7)
    (i32.store)
    (local.get $p)
    (i32.const 4)
    (i32.add)
    (i32.const 9)
    (i32.store)
    (local.get $p)
    (i32.load)
    (call $print_i32)
    (local.get $p)
    (i32.const 4)
    (i32.add)
    (i32.load)
    (call $print_i32)
  )
  
)
